name: Built and Lint 

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch

  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.txt'
      - 'docs/**'
      - .gitignore
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.txt'
      - 'docs/**'
      - .gitignore
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install the package in development mode
        pip install -e .

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    